### ISSUE TITLE
[Question] Does this work on all platform or only on WinUI ?

### ISSUE THREAD

**Issue by Strypper** [mhrastegari/MAUIWinUIAnimations#1]
Very impressive demo you have there but does this also work on Android and IOS? I see that you implement platform specific

**Comment by mhrastegari** [comment]
Thanks @Strypper ! yes this sample is only for Windows.

**Comment by mhrastegari** [comment]
But FYI, if you want to have custom animations in your `Xaml` for all platforms you can check out this amazing repo by @jsuarezruiz

https://github.com/jsuarezruiz/AlohaKit.Animations
